// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZS2Ig8R2jegaZLj2k639beFdNSs_2feA',
    appId: '1:103313973482:web:642e09f916243c9a817793',
    messagingSenderId: '103313973482',
    projectId: 'smarthomedoorlock-e9b6d',
    authDomain: 'smarthomedoorlock-e9b6d.firebaseapp.com',
    databaseURL: 'https://smarthomedoorlock-e9b6d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomedoorlock-e9b6d.firebasestorage.app',
    measurementId: 'G-MZZYWX6R18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKq2Sw0wOoqArPZROa2gnPSXIJ2u6WUIE',
    appId: '1:103313973482:android:ec4e05cde25847d0817793',
    messagingSenderId: '103313973482',
    projectId: 'smarthomedoorlock-e9b6d',
    databaseURL: 'https://smarthomedoorlock-e9b6d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomedoorlock-e9b6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBye4bvG5SIfzQEp8pntRSyoI8qrlhJ81I',
    appId: '1:103313973482:ios:5dbddf98c5fefba5817793',
    messagingSenderId: '103313973482',
    projectId: 'smarthomedoorlock-e9b6d',
    databaseURL: 'https://smarthomedoorlock-e9b6d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomedoorlock-e9b6d.firebasestorage.app',
    iosBundleId: 'com.example.smartDoorApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBye4bvG5SIfzQEp8pntRSyoI8qrlhJ81I',
    appId: '1:103313973482:ios:5dbddf98c5fefba5817793',
    messagingSenderId: '103313973482',
    projectId: 'smarthomedoorlock-e9b6d',
    databaseURL: 'https://smarthomedoorlock-e9b6d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomedoorlock-e9b6d.firebasestorage.app',
    iosBundleId: 'com.example.smartDoorApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZS2Ig8R2jegaZLj2k639beFdNSs_2feA',
    appId: '1:103313973482:web:2bde3f54c1e85cc4817793',
    messagingSenderId: '103313973482',
    projectId: 'smarthomedoorlock-e9b6d',
    authDomain: 'smarthomedoorlock-e9b6d.firebaseapp.com',
    databaseURL: 'https://smarthomedoorlock-e9b6d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smarthomedoorlock-e9b6d.firebasestorage.app',
    measurementId: 'G-T5FMHEBC0K',
  );
}
